### ISSUE TITLE
Post-Installation Suggestions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/www_old.julialang.org#522]
Related to the discussion at https://github.com/JuliaLang/julialang.github.com/pull/520 , the idea is that mentions of what to do post-installation should be gathered together. But I think that when putting this together, we establish some guidelines of

- What domains "matter" (why is plotting so important?)
- What packages/orgs should be mentioned (is PyPlot still "widely accepted" enough?)

I think that such a page should start with a quick introduction to the package manager, essentially stating that Julia can do lots of stuff due to its extensive package ecosystem, and you add packages with `Pkg.add`  and/or `Pkg.clone`. Then it should link to something that lists the packages. Though "not official", I think [Julia Observer](https://juliaobserver.com/) should be put in this official-looking role because it is the best online tool for this.

After that would go some suggestions. This is the part that is difficult and controversial since "picking winners" is always going to be controversial. There are three ways to go about doing this.

1. Stop mentioning any packages. Mentioning things like plotting packages was only done early on because it was a different time. One we get an introduction for how to find and install packages to a good state, this should be unnecessary.

2. Only mentioning tooling (IDE) packages. These aren't necessarily Julia packages, so they can be harder to find. But then, what tooling should be mentioned? Juno of course. VSCode? emacs and vim extensions?

3. Mention some standard tooling and packages, according to some guideline. I think a safe guideline is:

>If it's a standard feature of the MATLAB/SciPy/R core libraries, it deserves mention.

A quick list off the top of my head would be domains like

- Tooling
- Plotting
- Optimization
- Quadrature
- Differential Equations
- Interop
- File Formats
- Statistics

In some cases it could just mention orgs with a lot of packages in a domain (like for stats and opt), or it could mention specific ones. Of course, choosing the packages to mention would be controversial as well, but I would recommend that if we go with (3), then the choices for packages in the given domains would have some other criteria as well based on estimated usage through (bad, but still reasonable) indicators like Github stars.

I think (3) would be best for new users coming from technical computing in these other languages, because in many cases these things are expected to "just work" by new users. But I can see the potential controversy which would compel the eventual choice to be (1) or (2).

**Comment by ViralBShah** [comment]
If the purpose of this is meant to be a quick start guide to common things people do with Julia, there is no choice but to mention packages by name. When someone starts with Julia, they typically don't want too many options, but want to start doing something.

I think there isn't much of a controversy in which packages to recommend. We can always change the list if something better comes along. Plotting remains a top priority, but with Plots.jl, we should ideally have instructions that can get plots to work with no further thinking of what to get.

So long as packages we list here have reasonable tests, at least some documentation of exported APIs, active maintenance - I think those are ok to recommend.

**Comment by MikeInnes** [comment]
Another way to look at this is less "which packages do we want to promote/endorse" but more "what do we want a user's first experience to look like". Not everyone will need to do plotting day to day, but having a good experience trying out an IDE, running a couple of snippets and getting some nice visual feedback is something every new user can appreciate. Hopefully that will also get them interested enough to do more advanced stuff like grabbing packages they need.

**Comment by ViralBShah** [comment]
Plotting is the first thing people want. Load a csv file, do some simple operations, plot. Once comfortable with that workflow, everything else falls into place.

Cc @alanedelman

**Comment by ViralBShah** [comment]
Much of this is addressed in the new website. Finer grained issues should probably filed against the new website repo.
