### ISSUE TITLE
State of website translations

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www_old.julialang.org#549]
The language translations dropdown needs some work. I think it should probably be sorted by common languages and level of completeness. Also, the full list no longer shows because of the sheer number of translations.

In many cases, when I click on the translation, I almost always see the first paragraph in English, which probably would make someone think that the translation is incomplete.

Cc @Ismael-VC

**Comment by waldyrious** [comment]
@ViralBShah I started some work related to the dropdown in #551 (as discussed in #428); please review when you can.

**Comment by ViralBShah** [comment]
I wonder how effective the whole translation thing is. There are tons of languages, but on most of them, I just get English. Perhaps we should only show those which have at least 75% complete on the landing page?

**Comment by Ismael-VC** [comment]
@ViralBShah I'm on it!

**Comment by Ismael-VC** [comment]
@ViralBShah done, I'll promote translators and reviewers to complete the home page first.

![image](https://cloud.githubusercontent.com/assets/4594825/26032357/2651e276-3881-11e7-8e31-33c8c3b3c450.png)

**Comment by Ismael-VC** [comment]
These are the languages with at least 75% of translation and reviewing in the home page, many don't show the first paragraph translated, since it has changed and it needs to be reviewed again. I'll make everyone know about this.

**Comment by ViralBShah** [comment]
Ah, I see. 75% seems like a good bar. We can then have a link in that drop down for other languages where more translation is required.

**Comment by jebej** [comment]
Where are these translations? I could contribute.

**Comment by Ismael-VC** [comment]
@jebej the translation project is at:

* https://www.transifex.com/julialang-i18n/julialang-web

Thanks for your support! 👍

**Comment by ViralBShah** [comment]
Looks like we only have English and French now. Perhaps this translation stuff is not quite working out. How about we simply let Google translate take care of it?

**Comment by waldyrious** [comment]
> Perhaps this translation stuff is not quite working out.

@ViralBShah sorry for the long delay -- I just submitted #686. I trust that more people will start contributing once the prompt is presented in a more visible way. Let's give it a few months and see whether it improves the rate of translations.
