### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by pmargreff** [JuliaLang/www_old.julialang.org#567]
Hey there, someone can add me on translation team? 

Do u use transifex? If yes  -> pmargreff@gmail.com

**Comment by ChrisRackauckas** [comment]
@Ismael-VC

**Comment by Ismael-VC** [comment]
@pmargreff I'm on it, thanks for your support!

**Comment by Ismael-VC** [comment]
@pmargreff wellcome to the Julia-i18n project. I have added you as a translator to the Transifex team and also to the following chat rooms:

* https://gitter.im/JuliaLangPt/julia
* https://gitter.im/Julia-i18n/julia-i18n

Please let me know if there is anything else I can do to help you.

**Comment by ViralBShah** [comment]
If there is an active translation effort, please note in the `Community` section of the new website.
