### ISSUE TITLE
Improving the "learning" section

### ISSUE THREAD

**Issue by jmgnve** [JuliaLang/www_old.julialang.org#641]
I just thought I add this here for a discussion at a good time, or quick deletion :). It is mostly a copy from [this post](https://discourse.julialang.org/t/what-can-we-do-to-make-julia-grow-fast/6130/36?u=jmgnve) on discourse.

Would it help people to learn julia quicker if a few up-to-date tutorials about important topics where directly hosted on the julialang homepage, complementary to the docs? In particular tutorials (1) explaining how to actually use powerful julia concepts by a bunch of relevant examples, (2) explains how to avoid/handle common pitfalls that are julia specific, (3) tutorials showing central packages…

I think that would be a good "glue" between the quite simple first part of the docs, and the rather technical second part. My assumption is that it would help people (without a solid computer background like me) coming over the intermediate step easier (where I am quite stuck right now…). I would gladly try to contribute if there is a natural place where such educational stuff is hosted and maintained. However, tutorials are currently not updated, I realize that this is due to Julias rapid development right now. But later on, when 0.7/1.0 is out, would it make sence to host some tutorials on a “official” place, like the julialang page?

If you don´t think this is issue is relevant here, please simply close it. Otherwise, I would happily discuss the topic further at appropriate time ...

**Comment by ViralBShah** [comment]
Yes, definitely a good idea. We shouldn't spend too much time discussing it. Let's start putting some examples together of what this might look like.

**Comment by jmgnve** [comment]
Sounds good. In the summary of features on [julialang.org](https://julialang.org/), the following two topics come first:

- Multiple dispatch: providing ability to define function behavior across many combinations of argument types
- Dynamic type system: types for documentation, optimization, and dispatch

So I guess these two points are very important feautures of the language. Right? If yes, perhaps we should start there?

This [blog post](http://www.stochasticlifestyle.com/type-dispatch-design-post-object-oriented-programming-julia/) elaborates on that topic. Perhaps we can reuse some of that if the original author agrees? But move the machine code stuff to the end to make it easier, and make it more geared towards a real application?! Do you have a suggestion? Or an alternative for a better way forward? Are there any other old blog post etc we can reuse?

Finally, is it possible to add tests and code coverage to such tutorials? So that someone always can track whether they are up-to-date? I tried ones for myself to create a [tutorial package](https://github.com/jmgnve/Tutorials.jl) collecting what others have written, and tried to add some tests. Of course, that code is naive because I am a beginner, and I also gave up the effort quite quickly...

**Comment by ViralBShah** [comment]
Closing. Let's open a new issue on the new website repo. The current section is already improved over what we had but has a long way to go.
