### ISSUE TITLE
Donate button looks disabled

### ISSUE THREAD

**Issue by MikeInnes** [JuliaLang/www_old.julialang.org#683]
The donate button is greyed out with no hover effect, so it looks like it's not clickable for some reason.

**Comment by ViralBShah** [comment]
I think it is whatever NumFocus provided us. Good to fix it if possible.

**Comment by ararslan** [comment]
It does seem to work, it just looks like it's disabled. We might be able to change the color of it or something.

**Comment by ihnorton** [comment]
https://github.com/JuliaLang/julialang.github.com/blob/master/_layouts/common.html#L180

**Comment by ViralBShah** [comment]
Fixed in the new website.
