### ISSUE TITLE
Direct to a separate page rather than opening a popup from Donate Now

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/www_old.julialang.org#700]
I'm unclear on the details, but apparently Google Analytics isn't able to properly track donations that come from julialang.org because of the popup. I think this can be solved by directing people who click the Donate Now button to a separate donation page.

cc @shashi, @MikeInnes, @Dr-G

**Comment by Dr-G** [comment]
Correct. Kindly make it point here: https://www.flipcause.com/secure/cause_pdetails/MjI1Nw==

Thanks!

**Comment by ViralBShah** [comment]
Fixed in the new website.
