### ISSUE TITLE
Documentation on german 

### ISSUE THREAD

**Issue by christianbender** [JuliaLang/www_old.julialang.org#710]
In the moment I write a manual in german. 
https://github.com/JuliaLangGerman/Julia_Handbuch_Deutsch
How I can contribute to this repository?

**Comment by scls19fr** [comment]
Transifex could be the right place to provide a translation
https://www.transifex.com/julialang-i18n/julialang-web/dashboard/

**Comment by ViralBShah** [comment]
No longer using transifex.

**Comment by ViralBShah** [comment]
Do add this effort to the new `Community` section if relevant though.
