### ISSUE TITLE
Replace the Packages section with something more useful

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/www_old.julialang.org#732]
The topbar includes a `packages` link pointing to http://pkg.julialang.org, but it's almost useless for a newcomer looking for features given how many packages listed on that page. I think it would make sense to merge `packages` and `ecosystem` into a single page.  Before the list of organizations currently in the `ecosystems` page, it would point to a repository organizing all packages by features like http://svaksha.github.io/Julia.jl. Ideally we should bless an official or semi-official repository like that where package authors can register their packages, like R's [CRAN Task Views](https://cran.r-project.org/web/views/).

**Comment by ChrisRackauckas** [comment]
JuliaObserver.jl is a much better show of Julia's packages.

**Comment by ViralBShah** [comment]
Would people be ok with packages linking to juliaobserver.com?

**Comment by nalimilan** [comment]
That would certainly be useful. However, I'm not sure it would be enough to completely fill the role of [CRAN Task Views](https://cran.r-project.org/web/views/). What is lacking IMHO is:
- Categories should be grouped using a hierarchical structure, so that you can progressively find the narrowest category you're looking for instead of being lost in dozens of categories. I guess this can be fixed at any time in the Juliaobserver layout.
- The free-text format used by CRAN task views allows comparing similar or complementary packages and explaining why one would use one or the other (or both at the same time). This is probably not possible given how Juliaobserver is designed, so maybe we need two different way of navigating packages?

**Comment by ViralBShah** [comment]
Continued in https://github.com/JuliaLang/www.julialang.org/issues/21
